### ISSUE TITLE
Shell escaping issue ($ unescaped)

### ISSUE THREAD

**Issue by BuonOmo** [littlebee/git-log-utils#3]
Hi, I recently had an issue using git-time-machine (littlebee/git-time-machine#115). Working a little bit on it I figured out it came from this package:

# stacktrace

```
Error: Command failed: git log --pretty="format:{#/dquotes/id#/dquotes/: #/dquotes/%H#/dquotes/, #/dquotes/authorName#/dquotes/: #/dquotes/%an#/dquotes/, #/dquotes/relativeDate#/dquotes/: #/dquotes/%cr#/dquotes/, #/dquotes/authorDate#/dquotes/: %at,  #/dquotes/message#/dquotes/: #/dquotes/%s#/dquotes/, #/dquotes/body#/dquotes/: #/dquotes/%b#/dquotes/, #/dquotes/hash#/dquotes/: #/dquotes/%h#/dquotes/}" --topo-order --date=local --numstat /home/ubuonomo/dev/dashboard/app/js/assets/$asset.js
fatal: ambiguous argument '/home/ubuonomo/dev/dashboard/app/js/assets/.js': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at checkExecSyncError (child_process.js:481:13)
    at Object.execSync (child_process.js:521:13)
    at Function.module.exports.GitLogUtils._fetchFileHistory (/tmp/tmp.wDm6Cvzb3P/node_modules/git-log-utils/lib/git-log-utils.js:59:27)
    at Function.module.exports.GitLogUtils.getCommitHistory (/tmp/tmp.wDm6Cvzb3P/node_modules/git-log-utils/lib/git-log-utils.js:39:21)
    at Object.<anonymous> (/tmp/tmp.wDm6Cvzb3P/index.js:3:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

# Steps to reproduce

In a git repo containing a file starting with `$`, create and launch an index.js file containing the next lines:

```js
GitLogUtils = require('git-log-utils');
GitLogUtils.getCommitHistory("/<absolute_path_to_my_repo>/$<my_file>.js");
```

**Comment by BuonOmo** [comment]
@littlebee closing all my PRs and issues to avoid cluttering my personnal log. If you ever want to merge it, ping me here
